#!/bin/sh

. ${srcdir}/testing.sh

tst_start

com="../pybliographer -q ${srcdir}/../scripts/pybconvert.py"

run ${com} medline..bibtex ${srcdir}/medline.med > tmp.bib
run diff tmp.bib ${srcdir}/medline.bib
run rm -f tmp.bib

tst_stop

