#!/bin/sh

. testing.sh

tst_start

echo "- testing medline format"
run ../pybliographer -q import-export.py medline ${srcdir}/medline.med tmp.med
run ../pybliographer -q import-export.py medline tmp.med tmp2.med
run diff  tmp.med tmp2.med
run rm -f tmp.med tmp2.med

echo "- testing refer format"
run ../pybliographer -q import-export.py refer ${srcdir}/refer.refer tmp.refer
run ../pybliographer -q import-export.py refer tmp.refer tmp2.refer
run diff  tmp.refer tmp2.refer
run rm -f tmp.refer tmp2.refer

echo "- testing bibtex format"
run ../pybliographer -q import-export.py bibtex ${srcdir}/bibtex.bib tmp.bib
run ../pybliographer -q import-export.py bibtex tmp.bib tmp2.bib
run diff  tmp.bib tmp2.bib
run rm -f tmp.bib tmp2.bib

echo "- testing ovid format"
run ../pybliographer -q import-export.py ovid ${srcdir}/ovid.ovid tmp.ovid
run ../pybliographer -q import-export.py ovid tmp.ovid tmp2.ovid
run diff  tmp.ovid tmp2.ovid
run rm -f tmp.ovid tmp2.ovid

tst_stop

