/*
 * Translatable strings file generated by Glade.
 * Add this file to your project's POTFILES.in.
 * DO NOT compile it as part of your application.
 */

gchar *s = N_("Pybliographer");
gchar *s = N_("_New");
gchar *s = N_("Merge With...");
gchar *s = N_("Medline Query...");
gchar *s = N_("Previous Documents");
gchar *s = N_("_Add...");
gchar *s = N_("_Edit...");
gchar *s = N_("_Delete...");
gchar *s = N_("S_ort...");
gchar *s = N_("Cite");
gchar *s = N_("Cite...");
gchar *s = N_("Format...");
gchar *s = N_("Settings");
gchar *s = N_("Fields...");
gchar *s = N_("Entries...");
gchar *s = N_("Open File");
gchar *s = N_("Save File");
gchar *s = N_("Cite");
