/*
 * Translatable strings file generated by Glade.
 * Add this file to your project's POTFILES.in.
 * DO NOT compile it as part of your application.
 */

gchar *s = N_("Search");
gchar *s = N_("Search");
gchar *s = N_("Close");
gchar *s = N_("*");
gchar *s = N_("*");
gchar *s = N_("Field");
gchar *s = N_("Pattern");
gchar *s = N_("Simple Search");
gchar *s = N_("Search Command:");
gchar *s = N_("*");
gchar *s = N_("Expert Search");
