/* Automatically generated by po2tbl.sed from pybliographer.pot.  */

#if HAVE_CONFIG_H
# include <config.h>
#endif

#include "libgettext.h"

const struct _msg_ent _msg_tbl[] = {
  {"", 1},
  {"warning: can't import %s: %s", 2},
  {"Illegal year value", 3},
  {"Illegal month value", 4},
  {"Illegal day value", 5},
  {"in %s", 6},
  {"no input pipe `%s'", 7},
  {"no output pipe `%s'", 8},
  {"method `%s' provides no opener", 9},
  {"File `%s' does not exist", 10},
  {"don't know how to open `%s'", 11},
  {"method `%s' provides no iterator", 12},
  {"key `%s' is malformed", 13},
  {"%s:%d: key `%s' already defined", 14},
  {"Format entries", 15},
  {"Bibliography style:", 16},
  {"Select style", 17},
  {"Output format:", 18},
  {"Output File:", 19},
  {"Select output file", 20},
  {"Day", 21},
  {"Month", 22},
  {"Year", 23},
  {"Invalid day field in date", 24},
  {"Invalid month field in date", 25},
  {"Invalid year field in date", 26},
  {"Entry type", 27},
  {"Key", 28},
  {"Create Field", 29},
  {"Mandatory", 30},
  {"Optional", 31},
  {"Extra", 32},
  {"New text", 33},
  {"Error", 34},
  {"Invalid key format", 35},
  {"Key already exists", 36},
  {"Error in native string parsing", 37},
  {"Native Editing", 38},
  {"Standard Editing", 39},
  {"File", 40},
  {"Bibliography type:", 41},
  {"Add...", 42},
  {"Edit...", 43},
  {"Delete", 44},
  {"Search", 45},
  {"Field", 46},
  {"Pattern", 47},
  {"Simple Search", 48},
  {"Search command:", 49},
  {"Expert Search", 50},
  {"Full database", 51},
  {"internal error during evaluation", 52},
  {"\
while compiling %s\n\
error: %s", 53},
  {"Select sort criterions", 54},
  {"In use", 55},
  {"Sort criterions", 56},
  {"[Entry Type]", 57},
  {"[Key Value]", 58},
  {"Reorder", 59},
  {"Unselect all", 60},
  {"Yes", 61},
  {"\
The following errors occured:\n\
\n", 62},
  {"New", 63},
  {"Merge...", 64},
  {"Previous Documents", 65},
  {"About...", 66},
  {"Submit a Bug Report", 67},
  {"Sort...", 68},
  {"Cite", 69},
  {"Format...", 70},
  {"Edit", 71},
  {"Help", 72},
  {"Open", 73},
  {"Save", 74},
  {"Find", 75},
  {"Close", 76},
  {"\
can't open file `%s' for writing:\n\
%s", 77},
  {"New database", 78},
  {"[no entry]", 79},
  {"[1 entry]", 80},
  {"[%d entries]", 81},
  {"[%d/1 entry]", 82},
  {"[%d/%d entries]", 83},
  {"[modified]", 84},
  {"\
The database has been modified.\n\
Discard changes ?", 85},
  {"Merge file", 86},
  {"Open error", 87},
  {"Merge status", 88},
  {"Open file", 89},
  {"\
An internal error occured during saving\n\
Try to Save As...", 90},
  {"\
The file `%s' already exists.\n\
Overwrite it ?", 91},
  {"\
During opening:\n\
%s", 92},
  {"\
An entry called `%s' already exists.\n\
Rename and add it anyway ?", 93},
  {"Really remove all the entries ?", 94},
  {"Really edit %d entries ?", 95},
  {"Remove all the %d entries ?", 96},
  {"Remove entry `%s' ?", 97},
  {"\
Can't connect to LyX:\n\
%s", 98},
  {"\
Please install bug-buddy\n\
to use this feature", 99},
  {"This program is copyrighted under the GNU GPL", 100},
  {"Gnome interface to the Pybliographer system.", 101},
  {"Pybliographer Home Page", 102},
  {"This is %s, version %s", 103},
  {"This is free software with ABSOLUTELY NO WARRANTY.", 104},
  {"For details, type `warranty'.", 105},
  {"%s: error: can't open file `%s'", 106},
  {"For help, run %s and type `help' at the prompt", 107},
  {"\
Useful commands:\n\
\thelp     to get some help\n\
\tquit     to quit\n", 108},
};

int _msg_tbl_length = 108;
